In [1]:
#In class exercise 1(a)
import pandas as pd
video_games = pd.read_excel('video_games.xlsx')
video_games.head()

,Sales,Review_Score,Used_Price,Release_Year,Length_All_PlayStyles_Polled
0,4690.0,85,24.95,2004,57
1,560.0,89,14.95,2004,5
2,540.0,81,22.95,2004,57
3,490.0,81,12.95,2004,0
4,450.0,61,14.95,2004,37

In [5]:
#In class exercise 1(b)
import statsmodels.api as sm

y = video_games['Sales']

X = video_games.drop('Sales',axis=1) #this code drops the Sales variable so that you are left with all the other variables. The axis=1 part causes you to drop a column and not a row.
X = sm.add_constant(X)

model1 = sm.OLS(y,X[['const','Review_Score']]).fit() #note that the 'const' variable is the intercept
model2 = sm.OLS(y,X[['const','Used_Price']]).fit() 
model3 = sm.OLS(y,X[['const','Release_Year']]).fit() 
model4 = sm.OLS(y,X[['const','Length_All_PlayStyles_Polled']]).fit() 

print(model1.summary())
print(model2.summary())
print(model3.summary())
print(model4.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                  Sales   R-squared:                       0.089
Model:                            OLS   Adj. R-squared:                  0.088
Method:                 Least Squares   F-statistic:                     117.2
Date:                Wed, 24 Jun 2026   Prob (F-statistic):           4.01e-26
Time:                        12:19:19   Log-Likelihood:                -10077.
No. Observations:                1207   AIC:                         2.016e+04
Df Residuals:                    1205   BIC:                         2.017e+04
Df Model:                           1
Covariance Type:            nonrobust
================================================================================
                   coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------
const        -1188.9206    159.225     -7.467      0.000   -1501.310    -876.531
Review_Score    24.6019      2.273     10.825      0.000      20.143      29.061
==============================================================================
Omnibus:                     1569.551   Durbin-Watson:                   0.683
Prob(Omnibus):                  0.000   Jarque-Bera (JB):           245926.426
Skew:                           6.978   Prob(JB):                         0.00
Kurtosis:                      71.522   Cond. No.                         379.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
                            OLS Regression Results
==============================================================================
Dep. Variable:                  Sales   R-squared:                       0.068
Model:                            OLS   Adj. R-squared:                  0.068
Method:                 Least Squares   F-statistic:                     88.49
Date:                Wed, 24 Jun 2026   Prob (F-statistic):           2.49e-20
Time:                        12:19:19   Log-Likelihood:                -10091.
No. Observations:                1207   AIC:                         2.019e+04
Df Residuals:                    1205   BIC:                         2.020e+04
Df Model:                           1
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       -465.6668    107.387     -4.336      0.000    -676.353    -254.981
Used_Price    55.7992      5.932      9.407      0.000      44.161      67.437
==============================================================================
Omnibus:                     1499.423   Durbin-Watson:                   0.629
Prob(Omnibus):                  0.000   Jarque-Bera (JB):           198948.196
Skew:                           6.468   Prob(JB):                         0.00
Kurtosis:                      64.551   Cond. No.                         65.5
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
                            OLS Regression Results
==============================================================================
Dep. Variable:                  Sales   R-squared:                       0.000
Model:                            OLS   Adj. R-squared:                 -0.001
Method:                 Least Squares   F-statistic:                   0.07825
Date:                Wed, 24 Jun 2026   Prob (F-statistic):              0.780
Time:                        12:19:19   Log-Likelihood:                -10133.
No. Observations:                1207   AIC:                         2.027e+04
Df Residuals:                    1205   BIC:                         2.028e+04
Df Model:                           1
Covariance Type:            nonrobust
================================================================================
                   coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------
const           1.7e+04    5.9e+04      0.288      0.773   -9.87e+04    1.33e+05
Release_Year    -8.2215     29.392     -0.280      0.780     -65.886      49.443
==============================================================================
Omnibus:                     1531.168   Durbin-Watson:                   0.506
Prob(Omnibus):                  0.000   Jarque-Bera (JB):           197141.694
Skew:                           6.750   Prob(JB):                         0.00
Kurtosis:                      64.137   Cond. No.                     3.84e+06
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 3.84e+06. This might indicate that there are
strong multicollinearity or other numerical problems.
                            OLS Regression Results
==============================================================================
Dep. Variable:                  Sales   R-squared:                       0.062
Model:                            OLS   Adj. R-squared:                  0.061
Method:                 Least Squares   F-statistic:                     79.88
Date:                Wed, 24 Jun 2026   Prob (F-statistic):           1.46e-18
Time:                        12:19:19   Log-Likelihood:                -10095.
No. Observations:                1207   AIC:                         2.019e+04
Df Residuals:                    1205   BIC:                         2.020e+04
Df Model:                           1
Covariance Type:            nonrobust
================================================================================================
                                   coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                          428.0569     31.098     13.765      0.000     367.046     489.068
Length_All_PlayStyles_Polled     1.7225      0.193      8.937      0.000       1.344       2.101
==============================================================================
Omnibus:                     1567.721   Durbin-Watson:                   0.649
Prob(Omnibus):                  0.000   Jarque-Bera (JB):           239193.204
Skew:                           6.976   Prob(JB):                         0.00
Kurtosis:                      70.539   Cond. No.                         168.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

In [6]:
#In class exercise 1(c)
model5 = sm.OLS(y,X).fit()
print(model5.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                  Sales   R-squared:                       0.162
Model:                            OLS   Adj. R-squared:                  0.159
Method:                 Least Squares   F-statistic:                     58.15
Date:                Wed, 24 Jun 2026   Prob (F-statistic):           6.63e-45
Time:                        12:22:16   Log-Likelihood:                -10027.
No. Observations:                1207   AIC:                         2.006e+04
Df Residuals:                    1202   BIC:                         2.009e+04
Df Model:                           4
Covariance Type:            nonrobust
================================================================================================
                                   coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                         1.157e+05   5.51e+04      2.101      0.036    7634.158    2.24e+05
Review_Score                    17.9424      2.305      7.783      0.000      13.419      22.466
Used_Price                      46.4553      5.796      8.015      0.000      35.084      57.827
Release_Year                   -58.4524     27.454     -2.129      0.033    -112.316      -4.589
Length_All_PlayStyles_Polled     1.1107      0.193      5.759      0.000       0.732       1.489
==============================================================================
Omnibus:                     1570.332   Durbin-Watson:                   0.838
Prob(Omnibus):                  0.000   Jarque-Bera (JB):           275112.124
Skew:                           6.928   Prob(JB):                         0.00
Kurtosis:                      75.652   Cond. No.                     3.91e+06
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 3.91e+06. This might indicate that there are
strong multicollinearity or other numerical problems.

In [8]:
#Class Exercise 2(a)
import pandas as pd

insurance = pd.read_csv('insurance.csv')
insurance = pd.get_dummies(insurance, dtype=int)
insurance.head()

,age,bmi,children,charges,sex_female,sex_male,smoker_no,smoker_yes,region_northeast,region_northwest,region_southeast,region_southwest
0,19,27.900,0,16884.92400,1,0,0,1,0,0,0,1
1,18,33.770,1,1725.55230,0,1,1,0,0,0,1,0
2,28,33.000,3,4449.46200,0,1,1,0,0,0,1,0
3,33,22.705,0,21984.47061,0,1,1,0,0,1,0,0
4,32,28.880,0,3866.85520,0,1,1,0,0,1,0,0

In [10]:
#Class Exercise 2(b)
import statsmodels.api as sm

y = insurance['charges']
X = insurance['sex_male']
X = sm.add_constant(X)

model = sm.OLS(y,X).fit()
print(model.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                charges   R-squared:                       0.003
Model:                            OLS   Adj. R-squared:                  0.003
Method:                 Least Squares   F-statistic:                     4.400
Date:                Wed, 24 Jun 2026   Prob (F-statistic):             0.0361
Time:                        13:36:27   Log-Likelihood:                -14475.
No. Observations:                1338   AIC:                         2.895e+04
Df Residuals:                    1336   BIC:                         2.897e+04
Df Model:                           1
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       1.257e+04    470.072     26.740      0.000    1.16e+04    1.35e+04
sex_male    1387.1723    661.331      2.098      0.036      89.812    2684.532
==============================================================================
Omnibus:                      331.451   Durbin-Watson:                   2.011
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              636.534
Skew:                           1.496   Prob(JB):                    6.00e-139
Kurtosis:                       4.572   Cond. No.                         2.63
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

In [11]:
#Class Exercise 2(c)
import statsmodels.api as sm

y = insurance['charges']
X = insurance[['sex_male','smoker_yes']]
X = sm.add_constant(X)

model = sm.OLS(y,X).fit()
print(model.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                charges   R-squared:                       0.620
Model:                            OLS   Adj. R-squared:                  0.619
Method:                 Least Squares   F-statistic:                     1088.
Date:                Wed, 24 Jun 2026   Prob (F-statistic):          4.78e-281
Time:                        13:37:37   Log-Likelihood:                -13831.
No. Observations:                1338   AIC:                         2.767e+04
Df Residuals:                    1335   BIC:                         2.768e+04
Df Model:                           2
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       8466.0358    303.541     27.891      0.000    7870.566    9061.506
sex_male     -65.3784    409.809     -0.160      0.873    -869.318     738.561
smoker_yes  2.362e+04    507.736     46.524      0.000    2.26e+04    2.46e+04
==============================================================================
Omnibus:                      135.842   Durbin-Watson:                   2.025
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              211.897
Skew:                           0.727   Prob(JB):                     9.71e-47
Kurtosis:                       4.299   Cond. No.                         2.97
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.